### ISSUE TITLE
Deploy after latest update fails

### ISSUE THREAD

**Issue by jonfriesen** [zeplo/issue-tracker#1]
**CLI Version** 0.6.6

I updated the version and tried to run `zeplo deploy` and got the following:
```bash
$ zeplo deploy

The following errors/warnings where found in your service definition:

  [ERROR] Invalid specVersion, expected 1

Deployment failed due to errors in your service definition
```
my zeplo.yml looks like
```yaml
# Service Definition Specification Version
# (if you don't provide this you will be on latest, which may change without warning!)
specVersion: "v1"

# The name of your service
name: "megamaker/megamaker-weekly"

# Service will be assumed to be private unless this is explicitly set. This service
# will be accessible externally - only applies to the latest tag.
public: false

# Can either be HTTPS or RUN
# RUN mode is for executing long-running scripts. It runs until the script/code exists.
# HTTPS mode is for high frequency code. It requires you expose a HTTP server from your code.
mode: "RUN"

# Automatic triggers that will run the service (HTTP triggers are added automatically)
# triggers:
#   # Schedule the service to run every minute (https://crontab.guru)
#   - type: "schedule/cron"
#     cron: "0 7 * * 1"
#     timezone: "America/Vancouver"
#     # Will call the latest deployment - see tagging deployment https://zeplo.io/docs/zeplo-cli#deploy
#     tag: "latest"

# Build the contents of the directory (during deployment), and then run the compiled src at runtime
build:
  context: "."
  builder: "docker"

# Optionally provide environment variables / secrets
environment:
  - "SLACK_API_URL"
  - "DISCOURSE_API_KEY"
```
