### ISSUE TITLE
zeplo.yml /w triggers fail

### ISSUE THREAD

**Issue by jonfriesen** [zeplo/issue-tracker#2]
When pushing up code that looks like:

```yml
# Automatic triggers that will run the service (HTTP triggers are added automatically)
triggers:
  # Schedule the service to run every minute (https://crontab.guru)
  - type: "schedule/cron"
    options:
      cron: "0 7 * * 1"
      timezone: "America/Vancouver"
    # Will call the latest deployment - see tagging deployment https://zeplo.io/docs/zeplo-cli#deploy
    tag: "latest"
```

An error appears on deploy saying an error has been logged and will be looked at. 

Update:
It appears that my first failed deployment set the cron job, after commenting the above section out the deployment was successful.
